### ISSUE TITLE
[Feature Request] Ability to POST a single/multi-parted data

### ISSUE THREAD

**Issue by unsuitable001** [Sunbreak/cronet_flutter#12]
Add POST request capability to the library so we can send single/multi parted data to the server.

Utilizes - UploadDataProvider & UploadDataSink 

I think this can be used for PUT method also? (or, any other data sending method in general)

**Comment by Sunbreak** [comment]
Here is a prove of concept https://github.com/Sunbreak/cronet_flutter/tree/feature/post

**Comment by unsuitable001** [comment]
Is multi-parted uploads supported without chunked uploads? Any idea how to achieve multi-parted uploads? I'll also start studying about chunked uploads.

**Comment by Sunbreak** [comment]
Could you write some example/unitest to elaborate the usecase?

Or maybe some pesudo code with package [http](https://pub.dev/packages/http) or [dio](https://pub.dev/packages/dio) to post request to https://postman-echo.com

**Comment by unsuitable001** [comment]
Sure. I'll try to do that. What I mean is, can we use `multipart/form-data` as content-type? Do we need to make any changes from your current solution to do that? And, also if we want to upload multiple files at once like this:

https://stackoverflow.com/questions/913626/what-should-a-multipart-http-request-with-multiple-files-look-like

(Sorry for this novice question 😅)

Actually, I don't know any test/dummy api to test these. So, haven't got a scope to test them yet. Seems like I've to build one 😅

**Comment by Sunbreak** [comment]
Ref: https://github.com/Sunbreak/cronet_flutter/issues/14

Checkout https://github.com/unsuitable001/dart_cronet_sample for better usability
