### ISSUE TITLE
Does it support HTTP3?

### ISSUE THREAD

**Issue by bezubaba** [Sunbreak/cronet_flutter#16]
I tried https://pub.dev/packages/cronet but quic was somehow always falling back to TCP, http2

**Comment by Sunbreak** [comment]
I'm not familiar sure about QUIC.

Both https://github.com/google/cronet.dart and this repo are using Cronet-86.0.4240.198.

You could check if Android works with the wrapped version: https://developer.android.com/guide/topics/connectivity/cronet

---

BTW: [proto-quic](https://groups.google.com/a/chromium.org/g/proto-quic) or [net-dev](https://groups.google.com/a/chromium.org/g/net-dev) may be a better place to ask for help.

It is probable a config issue
